---
name: "Deploy GCP Resources"

on:
  push:
    branches:
      - main
    paths:
      - "terraform-config/**"

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
