name: "Create Sonarqube Docker Workflow"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: sonarqube scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=preciso_ghasd
            -Dsonar.organization=preciso
            -Dsonar.python.coverage.reportPaths=coverage.xml
